name: "ShareFS"
description: ""
inputs:
  path:
    description: "Path to share"
    required: true
runs:
  using: "composite"
  steps:
    - name: Cache
      uses: actions/cache@v3
      with:
        path: "${{ inputs.path }}"
        key: ${{ github.run_number }}-${{ inputs.path }}
